import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "@/styles/globals.css";
import Header from "@/components/ui/header/header";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} container p-4  antialiased font-sans`}>
				<Script
					type="module"
					src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
					strategy="beforeInteractive"
				/>
				<Script
					src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
					strategy="beforeInteractive"
				/>
				<Header />
				{children}
			</body>
		</html>
	);
}
