import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/ui/header/header";
import ProviderWrapper from "@/store/provider/provider-wrapper";

import "@/styles/globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ProviderWrapper>
				<body
					className={`${inter.variable} flex flex-col min-h-screen p-4 antialiased font-sans`}>
					<Header />
					{children}
				</body>
			</ProviderWrapper>
		</html>
	);
}
